[python binding] Fixup insn_name() to print the instruction name
_ascii_name_or_default(name, default) accept binary object, and
expect to call the decode() method.

Fixup : Avoid to call decode() twice as str don't have decode()

Python error : AttributeError: 'str' object has no attribute 'decode'